### ISSUE TITLE
Most likely my own mistake

### ISSUE THREAD

**Issue by ParagonHeart** [SunsetFi/bookofhours-catalog#2]
I downloaded the 'Never installed BepInEx' Zip file and extracted the entire file in the Steam > Common > Book of Hours folder and tried opening the link in the steam overlay web-client but I kept getting an error.  What did I do wrong?

**Comment by SunsetFi** [comment]
Sorry about that!  It was my mistake; I left a file out of the installer.  Please re-download the quickstart.

Make sure you get a BepInEx folder in your Book of Hours folder.  If it extracts to a "Hush House Catalogue Quickstart" folder, copy its contents back into the Book of Hours folder.

I'll leave this issue open, let me know when you have done that and if it works for you.

**Comment by ParagonHeart** [comment]
Did it and it worked!!  Thank you!!
