### ISSUE TITLE
Blank screen with 1.3.0

### ISSUE THREAD

**Issue by Eyrdan** [SunsetFi/bookofhours-catalog#4]
Just tried 1.3.0 but I just get a brief flash of the UI then the screen goes blank. All I see in console is:

react-BEjrUbGb.js:32 Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at Xr (index-c2_yNObl.js:1:12474)
    at index-c2_yNObl.js:1:11953
    at rxjs-CM6rVVJk.js:3:18071
    at a._next (rxjs-CM6rVVJk.js:3:5938)
    at r.next (rxjs-CM6rVVJk.js:3:2570)
    at rxjs-CM6rVVJk.js:3:7090
    at U (rxjs-CM6rVVJk.js:3:2322)
    at r.next (rxjs-CM6rVVJk.js:3:6885)
    at r.next (rxjs-CM6rVVJk.js:3:10259)
    at Object.next (rxjs-CM6rVVJk.js:3:22231)

Tried wiping the install and re-installing from the QuickStart zip, no change...

Did the same, going back to 1.2.0 and it works again.

**Comment by SunsetFi** [comment]
Sorry about that, there was an issue with the build tool messing up the production release.  Let me know if [1.4.0](https://github.com/SunsetFi/bookofhours-catalog/releases/tag/v1.4.0) fixes it for you.

**Comment by Eyrdan** [comment]
Yup, 1.4.0 fixed it. Thanks for the great work
